name: Notify on Push

on:
  push:
    branches:
      - main
      - testing

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Git Push Details
        id: git_details
        run: |
          echo "Push creator: ${{ github.event.sender.login }}"
          echo "Push project: ${{ github.event.repository.name }}"
          echo "Push url: ${{ github.event.compare }}"
          echo "PR title: ${{ github.event.pull_request.title }}"
          echo "PR body: ${{ github.event.pull_request.body }}"

      - name: Slack Notification
        run: |
          curl --location --request POST 'https://hooks.slack.com/services/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' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "text": "NEW PUSH by ${{ github.event.sender.login }}\n*Project:* ${{ github.event.repository.name }}\n*Branch:* ${{ github.event.ref }}\n*PR Title:* ${{ github.event.pull_request.title }}\n*PR Description:* ${{ github.event.pull_request.body }}\n*Details:* <${{ github.event.compare }}>"
          }'
